# Generated by Django 3.2.6 on 2021-08-25 05:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0002_auto_20210822_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='user',
            name='use',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='art',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
