# Generated by Django 3.2.6 on 2021-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_api', '0003_auto_20210825_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
